services:
  web:
    image: php:8.2-apache
    # penser à changer le nom du !!!! container !!!!
    container_name: php-apache-sql_leboncoin
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    ports:
      - "8000:80"
    networks:
      - app-network

networks:
  app-network: